In [204]:
#load the data

import csv
import pandas as pd
import numpy as np
import scipy as sp 
import math
with open('table.dat', 'r') as file:
    table = pd.read_csv(file, delimiter=',', header = None)

with open('msa.dat', 'r') as file:
    msa = pd.read_csv(file, delimiter=',', header = None)

with open('branchlength.dat', 'r') as file:
    brlen = pd.read_csv(file, delimiter=',', header = None)

msa[[0,1]] = msa[0].str.split(' ', expand=True)
msa[0] = pd.to_numeric(msa[0])
Q = np.array([[-0.5625,0.1875,0.1875,0.1875],[0.1875,-0.5625,0.1875,0.1875],
 [0.1875,0.1875,-0.5625,0.1875],[0.1875,0.1875,0.1875,-0.5625]])
print(table)
print(msa)
print(brlen)

   0  1
0  9  1
1  9  2
2  8  9
3  8  3
4  7  4
5  7  5
6  6  7
7  6  8
   0                               1
0  1  AGATCAAGATCAAGATCAAGATCAAGATCA
1  2  AGCTCAAGCTCAAGCTCAAGCTCAAGCTCA
2  3  CGCTATCGCTATCGCTATCGCTATCGCTAT
3  4  CGTTACCGTTACCGTTACCGTTACCGTTAC
4  5  CGCTACCGCTACCGCTACCGCTACCGCTAC
     0    1     2     3    4     5     6     7
0  0.1  0.4  0.01  0.04  0.2  0.08  0.12  0.14


In [155]:
print(msa[1].values[4])

CGCTACCGCTACCGCTACCGCTACCGCTAC


In [156]:
#define the class

class Node:
    def __init__(self, number, parent, sibling, seq, length, root):
        self.number = number
        self.parent = parent
        self.sibling = sibling
        self.seq = seq
        self.length = length
        self.root = root

    def add_probability_matrix(self, matrix):
        if hasattr(self, 'length') and self.length is not None:
            self.matrix = sp.linalg.expm(self.length * matrix)
        else:
            print("No length attribute found")
            self.matrix = None
    def add_seq_probability(self):
        base_prob = {"A": np.array([1,0,0,0]), "T":np.array([0,1,0,0]), "C" : np.array([0,0,1,0]), "G" : np.array([0,0,0,1])}
        map_values = np.vectorize(lambda x: base_prob[x], signature='()->(n)')
        if hasattr(self, 'seq') and self.seq is not None:
            self.prob = map_values(self.seq)
        else:
            print("No sequence attribute found")
            self.prob = None

class Tree:
    def __init__(self, position):
        self.position = position
    def fill_probability_matrix(self, matrix):
        for node in self.position:
            node.add_probability_matrix(matrix)
            node.add_seq_probability()
    def fill_probability_sequence(self):
        root_node = None
        for node in self.position:
            if node.root:
                root_node = node.number    

In [157]:
def create_node_list(tab, ms, brl):
    node_list = []
    nodes = {}
    branches = iter(brl.iloc[0])
    for i in range(len(tab[1])):
            
        itself = tab[1][i]
        parent =  tab[0][i]
        sib_index = [index for index, value in enumerate(tab[0]) if value == parent and tab[1][index] != itself]
        sibling = tab[1][sib_index[0]]
        branch = next(branches)
        sequence = np.array(list(ms[1].values[itself-1])) if itself in ms[0].values else None
        root = None       
        nodes[itself] = Node(itself, parent, sibling, sequence, branch, root)
        node_list.append(nodes[itself])
    for i in tab[0]:

        if i not in list(tab[1]):
            itself = i
            parent =  None
            sibling = None
            branch = None
            root = True
            sequence = np.array(list(ms[1][itself])) if itself in ms[0] else None
            nodes[itself] = Node(itself, parent, sibling, sequence, branch, root)
            node_list.append(nodes[itself])
            break
    return node_list

def find_node_by_number(node_list, number):
    for node in node_list:
        if node.number == number:
            return node
    return None

def find_node_by_sigling(node_list, number):
    for node in node_list:
        if node.number == find_node_by_number(node_list, number).sibling:
            return node
    return None
def find_node_by_parent(node_list, number):
    for node in node_list:
        if node.number == find_node_by_number(node_list, number).parent:
            return node
    return None

In [171]:
tree_test = Tree(create_node_list(table, msa, brlen))
print(tree_test.position)
tree_test.fill_probability_matrix(Q)
print(tree_test.position[0].prob)



[<__main__.Node object at 0x0000026F7FB34B50>, <__main__.Node object at 0x0000026F7FBFF880>, <__main__.Node object at 0x0000026F7FC202B0>, <__main__.Node object at 0x0000026F0106C970>, <__main__.Node object at 0x0000026F0106C910>, <__main__.Node object at 0x0000026F02995090>, <__main__.Node object at 0x0000026F029950C0>, <__main__.Node object at 0x0000026F02995060>, <__main__.Node object at 0x0000026F02995000>]
No sequence attribute found
No sequence attribute found
No sequence attribute found
No length attribute found
No sequence attribute found
[[1 0 0 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]]


In [199]:
for node in tree_test.position:
    sib = find_node_by_sigling(tree_test.position, node.number)
    parent = find_node_by_parent(tree_test.position, node.number)
    
    if node.root == False:
        if node.prob is not None and sib.prob is not None and parent.prob is None:
            vec1 = np.matmul(node.prob, node.matrix)
            vec2 = np.matmul(sib.prob, sib.matrix)
            vec_parent = vec1 * vec2
            parent.prob = vec_parent
        else:
            continue
    

In [215]:
#print(np.matmul(tree_test.position[2].prob, tree_test.position[2].matrix))

print([node.number for node in tree_test.position])
print([node.sibling for node in tree_test.position])
#print(tree_test.position[8].prob)
#print(find_node_by_number(tree_test.position, 4).seq)
#print([find_node_by_sigling(tree_test.position, node.number).number for node in tree_test.position])
npmm = np.matmul(tree_test.position[8].prob, np.array([0.25,0.25,0.25,0.25])) 
print(sum([math.log(npmm.flatten()[i]) for i in range(len(npmm.flatten()))]))
print(sum([node.length for node in tree_test.position if node.length is not None]))

[1, 2, 9, 3, 4, 5, 7, 8, 6]
[2, 1, 3, 9, 5, 4, 8, 7, None]
-188.20007684036113
1.0899999999999999


In [10]:
# Need to create function within the tree class to calculate the likelihood of the tree
#Create the likelyhood matrix of known sequences

base_prob = {"A": np.array([1,0,0,0]), "T":np.array([0,1,0,0]), "C" : np.array([0,0,1,0]), "G" : np.array([0,0,0,1])}
map_values = np.vectorize(lambda x: base_prob[x], signature='()->(n)')

seq_prob1 = map_values(tree_test.position[0].seq)
seq_prob2 = map_values(tree_test.position[1].seq)
Q = np.array([[-0.5625,0.1875,0.1875,0.1875],[0.1875,-0.5625,0.1875,0.1875],
 [0.1875,0.1875,-0.5625,0.1875],[0.1875,0.1875,0.1875,-0.5625]])

P1 = sp.linalg.expm(tree_test.position[0].length * Q ) 
P2 = sp.linalg.expm(tree_test.position[1].length * Q )
vec1 = np.matmul(seq_prob1, P1)
vec2 = np.matmul(seq_prob2, P2)
vec_root= vec1 * vec2
vec_root


array([[0.06128403, 0.00117047, 0.01455271, 0.00117047],
       [0.00117047, 0.00117047, 0.00117047, 0.76195554],
       [0.00117047, 0.00117047, 0.76195554, 0.00117047],
       [0.00117047, 0.76195554, 0.00117047, 0.00117047],
       [0.01455271, 0.00117047, 0.06128403, 0.00117047],
       [0.06128403, 0.01455271, 0.00117047, 0.00117047],
       [0.06128403, 0.00117047, 0.01455271, 0.00117047],
       [0.00117047, 0.00117047, 0.00117047, 0.76195554],
       [0.00117047, 0.00117047, 0.76195554, 0.00117047],
       [0.00117047, 0.76195554, 0.00117047, 0.00117047],
       [0.01455271, 0.00117047, 0.06128403, 0.00117047],
       [0.06128403, 0.01455271, 0.00117047, 0.00117047],
       [0.06128403, 0.00117047, 0.01455271, 0.00117047],
       [0.00117047, 0.00117047, 0.00117047, 0.76195554],
       [0.00117047, 0.00117047, 0.76195554, 0.00117047],
       [0.00117047, 0.76195554, 0.00117047, 0.00117047],
       [0.01455271, 0.00117047, 0.06128403, 0.00117047],
       [0.06128403, 0.01455271,